# Permalinks
permalink:           pretty

# Setup
title:               RoBlog
tagline:             Tips & Tricks for Devs
url:
paginate:            1
baseurl:             "https://robertdesonier.github.io/RoBlog/"
theme: time-machine

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Robert Desonier
  url:               https://github.com/RobertDeSonier
  email:             rob.desonier@yahoo.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/RobertDeSonier/RoBlog

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Pages to Link
pages_list:
  About: '/about'
  Archive: '/archive'
